services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://db:27017/demo
      - JAVA_OPTS=-XX:+UseZGC -XX:MaxRAMPercentage=75.0 -XX:+ZGenerational
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mongo-data:
